# Generated by Django 5.1.6 on 2025-02-12 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCare',
            fields=[
                ('care_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('feeding_time', models.TimeField()),
                ('food_type', models.CharField(max_length=50)),
                ('food_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('behavior', models.TextField()),
                ('grooming', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('caretaker', models.ForeignKey(limit_choices_to={'role': 'caretaker'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_care_records', to='medical_staff.cat')),
            ],
        ),
    ]
